//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Board.proto
// Note: requires additional types generated from: SharedEnumConfig.proto
namespace com.lvl6.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BoardLayoutProto")]
  public partial class BoardLayoutProto : global::ProtoBuf.IExtensible
  {
    public BoardLayoutProto() {}
    
    private int _boardId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"boardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int boardId
    {
      get { return _boardId; }
      set { _boardId = value; }
    }
    private int _height = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }
    private int _width = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int width
    {
      get { return _width; }
      set { _width = value; }
    }
    private int _orbElements = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"orbElements", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int orbElements
    {
      get { return _orbElements; }
      set { _orbElements = value; }
    }
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.BoardPropertyProto> _properties = new global::System.Collections.Generic.List<com.lvl6.proto.BoardPropertyProto>();
    [global::ProtoBuf.ProtoMember(5, Name=@"properties", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.BoardPropertyProto> properties
    {
      get { return _properties; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BoardPropertyProto")]
  public partial class BoardPropertyProto : global::ProtoBuf.IExtensible
  {
    public BoardPropertyProto() {}
    
    private int _boardPropertyId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"boardPropertyId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int boardPropertyId
    {
      get { return _boardPropertyId; }
      set { _boardPropertyId = value; }
    }
    private int _boardId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"boardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int boardId
    {
      get { return _boardId; }
      set { _boardId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _posX = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private int _posY = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posY
    {
      get { return _posY; }
      set { _posY = value; }
    }
    private com.lvl6.proto.Element _elem = com.lvl6.proto.Element.NO_ELEMENT;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"elem", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.Element.NO_ELEMENT)]
    public com.lvl6.proto.Element elem
    {
      get { return _elem; }
      set { _elem = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}