//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: City.proto
// Note: requires additional types generated from: Structure.proto
// Note: requires additional types generated from: User.proto
namespace com.lvl6.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserCityExpansionDataProto")]
  public partial class UserCityExpansionDataProto : global::ProtoBuf.IExtensible
  {
    public UserCityExpansionDataProto() {}
    

    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private int _xPosition = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"xPosition", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int xPosition
    {
      get { return _xPosition; }
      set { _xPosition = value; }
    }

    private int _yPosition = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"yPosition", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int yPosition
    {
      get { return _yPosition; }
      set { _yPosition = value; }
    }

    private bool _isExpanding = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isExpanding", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isExpanding
    {
      get { return _isExpanding; }
      set { _isExpanding = value; }
    }

    private long _expandStartTime = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"expandStartTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long expandStartTime
    {
      get { return _expandStartTime; }
      set { _expandStartTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CityExpansionCostProto")]
  public partial class CityExpansionCostProto : global::ProtoBuf.IExtensible
  {
    public CityExpansionCostProto() {}
    

    private int _expansionNum = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"expansionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int expansionNum
    {
      get { return _expansionNum; }
      set { _expansionNum = value; }
    }

    private int _expansionCost = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"expansionCost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int expansionCost
    {
      get { return _expansionCost; }
      set { _expansionCost = value; }
    }

    private int _numMinutesToExpand = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"numMinutesToExpand", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numMinutesToExpand
    {
      get { return _numMinutesToExpand; }
      set { _numMinutesToExpand = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CityElementProto")]
  public partial class CityElementProto : global::ProtoBuf.IExtensible
  {
    public CityElementProto() {}
    

    private int _cityId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cityId
    {
      get { return _cityId; }
      set { _cityId = value; }
    }

    private int _assetId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"assetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int assetId
    {
      get { return _assetId; }
      set { _assetId = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private com.lvl6.proto.CityElementProto.CityElemType _type = com.lvl6.proto.CityElementProto.CityElemType.BUILDING;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.CityElementProto.CityElemType.BUILDING)]
    public com.lvl6.proto.CityElementProto.CityElemType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private com.lvl6.proto.CoordinateProto _coords = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"coords", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.CoordinateProto coords
    {
      get { return _coords; }
      set { _coords = value; }
    }

    private int _xLength = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"xLength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int xLength
    {
      get { return _xLength; }
      set { _xLength = value; }
    }

    private int _yLength = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"yLength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int yLength
    {
      get { return _yLength; }
      set { _yLength = value; }
    }

    private string _imgId = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"imgId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string imgId
    {
      get { return _imgId; }
      set { _imgId = value; }
    }

    private com.lvl6.proto.StructOrientation _orientation = com.lvl6.proto.StructOrientation.POSITION_1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"orientation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.StructOrientation.POSITION_1)]
    public com.lvl6.proto.StructOrientation orientation
    {
      get { return _orientation; }
      set { _orientation = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"CityElemType")]
    public enum CityElemType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUILDING", Value=1)]
      BUILDING = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DECORATION", Value=2)]
      DECORATION = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PERSON_NEUTRAL_ENEMY", Value=3)]
      PERSON_NEUTRAL_ENEMY = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOSS", Value=4)]
      BOSS = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FullCityProto")]
  public partial class FullCityProto : global::ProtoBuf.IExtensible
  {
    public FullCityProto() {}
    

    private int _cityId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cityId
    {
      get { return _cityId; }
      set { _cityId = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _mapImgName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mapImgName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mapImgName
    {
      get { return _mapImgName; }
      set { _mapImgName = value; }
    }

    private com.lvl6.proto.CoordinateProto _center = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"center", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.CoordinateProto center
    {
      get { return _center; }
      set { _center = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _taskIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"taskIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> taskIds
    {
      get { return _taskIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}