//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EventTournament.proto
// Note: requires additional types generated from: TournamentStuff.proto
// Note: requires additional types generated from: User.proto
namespace com.lvl6.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetrieveTournamentRankingsRequestProto")]
  public partial class RetrieveTournamentRankingsRequestProto : global::ProtoBuf.IExtensible
  {
    public RetrieveTournamentRankingsRequestProto() {}
    
    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private int _eventId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"eventId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int eventId
    {
      get { return _eventId; }
      set { _eventId = value; }
    }
    private int _afterThisRank = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"afterThisRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int afterThisRank
    {
      get { return _afterThisRank; }
      set { _afterThisRank = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetrieveTournamentRankingsResponseProto")]
  public partial class RetrieveTournamentRankingsResponseProto : global::ProtoBuf.IExtensible
  {
    public RetrieveTournamentRankingsResponseProto() {}
    
    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private com.lvl6.proto.RetrieveTournamentRankingsResponseProto.RetrieveTournamentStatus _status = com.lvl6.proto.RetrieveTournamentRankingsResponseProto.RetrieveTournamentStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.RetrieveTournamentRankingsResponseProto.RetrieveTournamentStatus.SUCCESS)]
    public com.lvl6.proto.RetrieveTournamentRankingsResponseProto.RetrieveTournamentStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _eventId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"eventId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int eventId
    {
      get { return _eventId; }
      set { _eventId = value; }
    }
    private int _afterThisRank = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"afterThisRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int afterThisRank
    {
      get { return _afterThisRank; }
      set { _afterThisRank = value; }
    }
    private com.lvl6.proto.MinimumUserProtoWithLevelForTournament _retriever = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"retriever", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProtoWithLevelForTournament retriever
    {
      get { return _retriever; }
      set { _retriever = value; }
    }
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.MinimumUserProtoWithLevelForTournament> _resultPlayers = new global::System.Collections.Generic.List<com.lvl6.proto.MinimumUserProtoWithLevelForTournament>();
    [global::ProtoBuf.ProtoMember(6, Name=@"resultPlayers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.MinimumUserProtoWithLevelForTournament> resultPlayers
    {
      get { return _resultPlayers; }
    }
  
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.FullUserProto> _fullUsers = new global::System.Collections.Generic.List<com.lvl6.proto.FullUserProto>();
    [global::ProtoBuf.ProtoMember(7, Name=@"fullUsers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.FullUserProto> fullUsers
    {
      get { return _fullUsers; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RetrieveTournamentStatus")]
    public enum RetrieveTournamentStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER_FAIL", Value=2)]
      OTHER_FAIL = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}