//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EventMonster.proto
// Note: requires additional types generated from: MonsterStuff.proto
// Note: requires additional types generated from: User.proto
namespace com.lvl6.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EvolveMonsterRequestProto")]
  public partial class EvolveMonsterRequestProto : global::ProtoBuf.IExtensible
  {
    public EvolveMonsterRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.UserMonsterEvolutionProto _evolution = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"evolution", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.UserMonsterEvolutionProto evolution
    {
      get { return _evolution; }
      set { _evolution = value; }
    }

    private int _gemsSpent = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gemsSpent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gemsSpent
    {
      get { return _gemsSpent; }
      set { _gemsSpent = value; }
    }

    private int _oilChange = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"oilChange", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int oilChange
    {
      get { return _oilChange; }
      set { _oilChange = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EvolveMonsterResponseProto")]
  public partial class EvolveMonsterResponseProto : global::ProtoBuf.IExtensible
  {
    public EvolveMonsterResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.EvolveMonsterResponseProto.EvolveMonsterStatus _status = com.lvl6.proto.EvolveMonsterResponseProto.EvolveMonsterStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.EvolveMonsterResponseProto.EvolveMonsterStatus.SUCCESS)]
    public com.lvl6.proto.EvolveMonsterResponseProto.EvolveMonsterStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"EvolveMonsterStatus")]
    public enum EvolveMonsterStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_INSUFFICIENT_GEMS", Value=2)]
      FAIL_INSUFFICIENT_GEMS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_INSUFFICIENT_RESOURCES", Value=3)]
      FAIL_INSUFFICIENT_RESOURCES = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_MONSTER_REACHED_EVOLVING_LIMIT", Value=4)]
      FAIL_MONSTER_REACHED_EVOLVING_LIMIT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_MAX_NUM_EVOLUTIONS_REACHED", Value=5)]
      FAIL_MAX_NUM_EVOLUTIONS_REACHED = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_NONEXISTENT_MONSTERS", Value=6)]
      FAIL_NONEXISTENT_MONSTERS = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=7)]
      FAIL_OTHER = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EvolutionFinishedRequestProto")]
  public partial class EvolutionFinishedRequestProto : global::ProtoBuf.IExtensible
  {
    public EvolutionFinishedRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private int _gemsSpent = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gemsSpent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gemsSpent
    {
      get { return _gemsSpent; }
      set { _gemsSpent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EvolutionFinishedResponseProto")]
  public partial class EvolutionFinishedResponseProto : global::ProtoBuf.IExtensible
  {
    public EvolutionFinishedResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.FullUserMonsterProto _evolvedMonster = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"evolvedMonster", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.FullUserMonsterProto evolvedMonster
    {
      get { return _evolvedMonster; }
      set { _evolvedMonster = value; }
    }

    private com.lvl6.proto.EvolutionFinishedResponseProto.EvolutionFinishedStatus _status = com.lvl6.proto.EvolutionFinishedResponseProto.EvolutionFinishedStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.EvolutionFinishedResponseProto.EvolutionFinishedStatus.SUCCESS)]
    public com.lvl6.proto.EvolutionFinishedResponseProto.EvolutionFinishedStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"EvolutionFinishedStatus")]
    public enum EvolutionFinishedStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_INSUFFICIENT_GEMS", Value=2)]
      FAIL_INSUFFICIENT_GEMS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=3)]
      FAIL_OTHER = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubmitMonsterEnhancementRequestProto")]
  public partial class SubmitMonsterEnhancementRequestProto : global::ProtoBuf.IExtensible
  {
    public SubmitMonsterEnhancementRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProtoWithMaxResources _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProtoWithMaxResources sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.UserEnhancementItemProto> _ueipDelete = new global::System.Collections.Generic.List<com.lvl6.proto.UserEnhancementItemProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ueipDelete", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.UserEnhancementItemProto> ueipDelete
    {
      get { return _ueipDelete; }
    }
  
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.UserEnhancementItemProto> _ueipUpdate = new global::System.Collections.Generic.List<com.lvl6.proto.UserEnhancementItemProto>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ueipUpdate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.UserEnhancementItemProto> ueipUpdate
    {
      get { return _ueipUpdate; }
    }
  
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.UserEnhancementItemProto> _ueipNew = new global::System.Collections.Generic.List<com.lvl6.proto.UserEnhancementItemProto>();
    [global::ProtoBuf.ProtoMember(4, Name=@"ueipNew", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.UserEnhancementItemProto> ueipNew
    {
      get { return _ueipNew; }
    }
  

    private int _gemsSpent = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gemsSpent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gemsSpent
    {
      get { return _gemsSpent; }
      set { _gemsSpent = value; }
    }

    private int _oilChange = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"oilChange", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int oilChange
    {
      get { return _oilChange; }
      set { _oilChange = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubmitMonsterEnhancementResponseProto")]
  public partial class SubmitMonsterEnhancementResponseProto : global::ProtoBuf.IExtensible
  {
    public SubmitMonsterEnhancementResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProtoWithMaxResources _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProtoWithMaxResources sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.SubmitMonsterEnhancementResponseProto.SubmitMonsterEnhancementStatus _status = com.lvl6.proto.SubmitMonsterEnhancementResponseProto.SubmitMonsterEnhancementStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.SubmitMonsterEnhancementResponseProto.SubmitMonsterEnhancementStatus.SUCCESS)]
    public com.lvl6.proto.SubmitMonsterEnhancementResponseProto.SubmitMonsterEnhancementStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"SubmitMonsterEnhancementStatus")]
    public enum SubmitMonsterEnhancementStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_INSUFFICIENT_GEMS", Value=2)]
      FAIL_INSUFFICIENT_GEMS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_INSUFFICIENT_OIL", Value=3)]
      FAIL_INSUFFICIENT_OIL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=4)]
      FAIL_OTHER = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnhancementWaitTimeCompleteRequestProto")]
  public partial class EnhancementWaitTimeCompleteRequestProto : global::ProtoBuf.IExtensible
  {
    public EnhancementWaitTimeCompleteRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private bool _isSpeedup = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isSpeedup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isSpeedup
    {
      get { return _isSpeedup; }
      set { _isSpeedup = value; }
    }

    private int _gemsForSpeedup = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gemsForSpeedup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gemsForSpeedup
    {
      get { return _gemsForSpeedup; }
      set { _gemsForSpeedup = value; }
    }

    private com.lvl6.proto.UserMonsterCurrentExpProto _umcep = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"umcep", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.UserMonsterCurrentExpProto umcep
    {
      get { return _umcep; }
      set { _umcep = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _userMonsterIds = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(5, Name=@"userMonsterIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> userMonsterIds
    {
      get { return _userMonsterIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnhancementWaitTimeCompleteResponseProto")]
  public partial class EnhancementWaitTimeCompleteResponseProto : global::ProtoBuf.IExtensible
  {
    public EnhancementWaitTimeCompleteResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.EnhancementWaitTimeCompleteResponseProto.EnhancementWaitTimeCompleteStatus _status = com.lvl6.proto.EnhancementWaitTimeCompleteResponseProto.EnhancementWaitTimeCompleteStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.EnhancementWaitTimeCompleteResponseProto.EnhancementWaitTimeCompleteStatus.SUCCESS)]
    public com.lvl6.proto.EnhancementWaitTimeCompleteResponseProto.EnhancementWaitTimeCompleteStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"EnhancementWaitTimeCompleteStatus")]
    public enum EnhancementWaitTimeCompleteStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_HEALING_NOT_COMPLETE", Value=2)]
      FAIL_HEALING_NOT_COMPLETE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_INSUFFICIENT_FUNDS", Value=3)]
      FAIL_INSUFFICIENT_FUNDS = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=4)]
      FAIL_OTHER = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateMonsterHealthRequestProto")]
  public partial class UpdateMonsterHealthRequestProto : global::ProtoBuf.IExtensible
  {
    public UpdateMonsterHealthRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterCurrentHealthProto> _umchp = new global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterCurrentHealthProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"umchp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterCurrentHealthProto> umchp
    {
      get { return _umchp; }
    }
  

    private long _clientTime = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"clientTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long clientTime
    {
      get { return _clientTime; }
      set { _clientTime = value; }
    }

    private long _userTaskId = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"userTaskId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userTaskId
    {
      get { return _userTaskId; }
      set { _userTaskId = value; }
    }

    private bool _isUpdateTaskStageForUser = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isUpdateTaskStageForUser", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isUpdateTaskStageForUser
    {
      get { return _isUpdateTaskStageForUser; }
      set { _isUpdateTaskStageForUser = value; }
    }

    private int _nuTaskStageId = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"nuTaskStageId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nuTaskStageId
    {
      get { return _nuTaskStageId; }
      set { _nuTaskStageId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateMonsterHealthResponseProto")]
  public partial class UpdateMonsterHealthResponseProto : global::ProtoBuf.IExtensible
  {
    public UpdateMonsterHealthResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.UpdateMonsterHealthResponseProto.UpdateMonsterHealthStatus _status = com.lvl6.proto.UpdateMonsterHealthResponseProto.UpdateMonsterHealthStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.UpdateMonsterHealthResponseProto.UpdateMonsterHealthStatus.SUCCESS)]
    public com.lvl6.proto.UpdateMonsterHealthResponseProto.UpdateMonsterHealthStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"UpdateMonsterHealthStatus")]
    public enum UpdateMonsterHealthStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_INSUFFICIENT_FUNDS", Value=2)]
      FAIL_INSUFFICIENT_FUNDS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=3)]
      FAIL_OTHER = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HealMonsterRequestProto")]
  public partial class HealMonsterRequestProto : global::ProtoBuf.IExtensible
  {
    public HealMonsterRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProtoWithMaxResources _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProtoWithMaxResources sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterHealingProto> _umhDelete = new global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterHealingProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"umhDelete", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterHealingProto> umhDelete
    {
      get { return _umhDelete; }
    }
  
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterHealingProto> _umhUpdate = new global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterHealingProto>();
    [global::ProtoBuf.ProtoMember(3, Name=@"umhUpdate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterHealingProto> umhUpdate
    {
      get { return _umhUpdate; }
    }
  
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterHealingProto> _umhNew = new global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterHealingProto>();
    [global::ProtoBuf.ProtoMember(4, Name=@"umhNew", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterHealingProto> umhNew
    {
      get { return _umhNew; }
    }
  

    private int _cashChange = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"cashChange", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cashChange
    {
      get { return _cashChange; }
      set { _cashChange = value; }
    }

    private int _gemCostForHealing = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gemCostForHealing", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gemCostForHealing
    {
      get { return _gemCostForHealing; }
      set { _gemCostForHealing = value; }
    }

    private bool _isSpeedup = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isSpeedup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isSpeedup
    {
      get { return _isSpeedup; }
      set { _isSpeedup = value; }
    }

    private int _gemsForSpeedup = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"gemsForSpeedup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gemsForSpeedup
    {
      get { return _gemsForSpeedup; }
      set { _gemsForSpeedup = value; }
    }
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterCurrentHealthProto> _umchp = new global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterCurrentHealthProto>();
    [global::ProtoBuf.ProtoMember(9, Name=@"umchp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterCurrentHealthProto> umchp
    {
      get { return _umchp; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HealMonsterResponseProto")]
  public partial class HealMonsterResponseProto : global::ProtoBuf.IExtensible
  {
    public HealMonsterResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProtoWithMaxResources _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProtoWithMaxResources sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.HealMonsterResponseProto.HealMonsterStatus _status = com.lvl6.proto.HealMonsterResponseProto.HealMonsterStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.HealMonsterResponseProto.HealMonsterStatus.SUCCESS)]
    public com.lvl6.proto.HealMonsterResponseProto.HealMonsterStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"HealMonsterStatus")]
    public enum HealMonsterStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_INSUFFICIENT_FUNDS", Value=2)]
      FAIL_INSUFFICIENT_FUNDS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_ALL_MONSTERS_ALREADY_HEALING", Value=3)]
      FAIL_ALL_MONSTERS_ALREADY_HEALING = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_ALL_MONSTERS_NONEXISTENT", Value=4)]
      FAIL_ALL_MONSTERS_NONEXISTENT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=5)]
      FAIL_OTHER = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_HEALING_NOT_COMPLETE", Value=6)]
      FAIL_HEALING_NOT_COMPLETE = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddMonsterToBattleTeamRequestProto")]
  public partial class AddMonsterToBattleTeamRequestProto : global::ProtoBuf.IExtensible
  {
    public AddMonsterToBattleTeamRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private int _teamSlotNum = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"teamSlotNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int teamSlotNum
    {
      get { return _teamSlotNum; }
      set { _teamSlotNum = value; }
    }

    private long _userMonsterId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userMonsterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userMonsterId
    {
      get { return _userMonsterId; }
      set { _userMonsterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddMonsterToBattleTeamResponseProto")]
  public partial class AddMonsterToBattleTeamResponseProto : global::ProtoBuf.IExtensible
  {
    public AddMonsterToBattleTeamResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.AddMonsterToBattleTeamResponseProto.AddMonsterToBattleTeamStatus _status = com.lvl6.proto.AddMonsterToBattleTeamResponseProto.AddMonsterToBattleTeamStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.AddMonsterToBattleTeamResponseProto.AddMonsterToBattleTeamStatus.SUCCESS)]
    public com.lvl6.proto.AddMonsterToBattleTeamResponseProto.AddMonsterToBattleTeamStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"AddMonsterToBattleTeamStatus")]
    public enum AddMonsterToBattleTeamStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=2)]
      FAIL_OTHER = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveMonsterFromBattleTeamRequestProto")]
  public partial class RemoveMonsterFromBattleTeamRequestProto : global::ProtoBuf.IExtensible
  {
    public RemoveMonsterFromBattleTeamRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private long _userMonsterId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userMonsterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userMonsterId
    {
      get { return _userMonsterId; }
      set { _userMonsterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveMonsterFromBattleTeamResponseProto")]
  public partial class RemoveMonsterFromBattleTeamResponseProto : global::ProtoBuf.IExtensible
  {
    public RemoveMonsterFromBattleTeamResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.RemoveMonsterFromBattleTeamResponseProto.RemoveMonsterFromBattleTeamStatus _status = com.lvl6.proto.RemoveMonsterFromBattleTeamResponseProto.RemoveMonsterFromBattleTeamStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.RemoveMonsterFromBattleTeamResponseProto.RemoveMonsterFromBattleTeamStatus.SUCCESS)]
    public com.lvl6.proto.RemoveMonsterFromBattleTeamResponseProto.RemoveMonsterFromBattleTeamStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RemoveMonsterFromBattleTeamStatus")]
    public enum RemoveMonsterFromBattleTeamStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=2)]
      FAIL_OTHER = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IncreaseMonsterInventorySlotRequestProto")]
  public partial class IncreaseMonsterInventorySlotRequestProto : global::ProtoBuf.IExtensible
  {
    public IncreaseMonsterInventorySlotRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.IncreaseMonsterInventorySlotRequestProto.IncreaseSlotType _increaseSlotType = com.lvl6.proto.IncreaseMonsterInventorySlotRequestProto.IncreaseSlotType.PURCHASE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"increaseSlotType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.IncreaseMonsterInventorySlotRequestProto.IncreaseSlotType.PURCHASE)]
    public com.lvl6.proto.IncreaseMonsterInventorySlotRequestProto.IncreaseSlotType increaseSlotType
    {
      get { return _increaseSlotType; }
      set { _increaseSlotType = value; }
    }

    private int _userStructId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userStructId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userStructId
    {
      get { return _userStructId; }
      set { _userStructId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _userFbInviteForSlotIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"userFbInviteForSlotIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> userFbInviteForSlotIds
    {
      get { return _userFbInviteForSlotIds; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"IncreaseSlotType")]
    public enum IncreaseSlotType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PURCHASE", Value=1)]
      PURCHASE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REDEEM_FACEBOOK_INVITES", Value=2)]
      REDEEM_FACEBOOK_INVITES = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IncreaseMonsterInventorySlotResponseProto")]
  public partial class IncreaseMonsterInventorySlotResponseProto : global::ProtoBuf.IExtensible
  {
    public IncreaseMonsterInventorySlotResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.IncreaseMonsterInventorySlotResponseProto.IncreaseMonsterInventorySlotStatus _status = com.lvl6.proto.IncreaseMonsterInventorySlotResponseProto.IncreaseMonsterInventorySlotStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.IncreaseMonsterInventorySlotResponseProto.IncreaseMonsterInventorySlotStatus.SUCCESS)]
    public com.lvl6.proto.IncreaseMonsterInventorySlotResponseProto.IncreaseMonsterInventorySlotStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"IncreaseMonsterInventorySlotStatus")]
    public enum IncreaseMonsterInventorySlotStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_INSUFFICIENT_FUNDS", Value=2)]
      FAIL_INSUFFICIENT_FUNDS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_INSUFFICIENT_FACEBOOK_INVITES", Value=3)]
      FAIL_INSUFFICIENT_FACEBOOK_INVITES = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=4)]
      FAIL_OTHER = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_INCONSISTENT_INVITE_DATA", Value=5)]
      FAIL_INCONSISTENT_INVITE_DATA = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_STRUCTURE_AT_MAX_FB_INVITE_LVL", Value=6)]
      FAIL_STRUCTURE_AT_MAX_FB_INVITE_LVL = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InviteFbFriendsForSlotsRequestProto")]
  public partial class InviteFbFriendsForSlotsRequestProto : global::ProtoBuf.IExtensible
  {
    public InviteFbFriendsForSlotsRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProtoWithFacebookId _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProtoWithFacebookId sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.InviteFbFriendsForSlotsRequestProto.FacebookInviteStructure> _invites = new global::System.Collections.Generic.List<com.lvl6.proto.InviteFbFriendsForSlotsRequestProto.FacebookInviteStructure>();
    [global::ProtoBuf.ProtoMember(2, Name=@"invites", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.InviteFbFriendsForSlotsRequestProto.FacebookInviteStructure> invites
    {
      get { return _invites; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FacebookInviteStructure")]
  public partial class FacebookInviteStructure : global::ProtoBuf.IExtensible
  {
    public FacebookInviteStructure() {}
    

    private string _fbFriendId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fbFriendId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fbFriendId
    {
      get { return _fbFriendId; }
      set { _fbFriendId = value; }
    }

    private int _userStructId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userStructId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userStructId
    {
      get { return _userStructId; }
      set { _userStructId = value; }
    }

    private int _userStructFbLvl = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userStructFbLvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userStructFbLvl
    {
      get { return _userStructFbLvl; }
      set { _userStructFbLvl = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InviteFbFriendsForSlotsResponseProto")]
  public partial class InviteFbFriendsForSlotsResponseProto : global::ProtoBuf.IExtensible
  {
    public InviteFbFriendsForSlotsResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProtoWithFacebookId _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProtoWithFacebookId sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.InviteFbFriendsForSlotsResponseProto.InviteFbFriendsForSlotsStatus _status = com.lvl6.proto.InviteFbFriendsForSlotsResponseProto.InviteFbFriendsForSlotsStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.InviteFbFriendsForSlotsResponseProto.InviteFbFriendsForSlotsStatus.SUCCESS)]
    public com.lvl6.proto.InviteFbFriendsForSlotsResponseProto.InviteFbFriendsForSlotsStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.UserFacebookInviteForSlotProto> _invitesNew = new global::System.Collections.Generic.List<com.lvl6.proto.UserFacebookInviteForSlotProto>();
    [global::ProtoBuf.ProtoMember(3, Name=@"invitesNew", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.UserFacebookInviteForSlotProto> invitesNew
    {
      get { return _invitesNew; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"InviteFbFriendsForSlotsStatus")]
    public enum InviteFbFriendsForSlotsStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=2)]
      FAIL_OTHER = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcceptAndRejectFbInviteForSlotsRequestProto")]
  public partial class AcceptAndRejectFbInviteForSlotsRequestProto : global::ProtoBuf.IExtensible
  {
    public AcceptAndRejectFbInviteForSlotsRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProtoWithFacebookId _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProtoWithFacebookId sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _acceptedInviteIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"acceptedInviteIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> acceptedInviteIds
    {
      get { return _acceptedInviteIds; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _rejectedInviteIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rejectedInviteIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> rejectedInviteIds
    {
      get { return _rejectedInviteIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcceptAndRejectFbInviteForSlotsResponseProto")]
  public partial class AcceptAndRejectFbInviteForSlotsResponseProto : global::ProtoBuf.IExtensible
  {
    public AcceptAndRejectFbInviteForSlotsResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProtoWithFacebookId _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProtoWithFacebookId sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.AcceptAndRejectFbInviteForSlotsResponseProto.AcceptAndRejectFbInviteForSlotsStatus _status = com.lvl6.proto.AcceptAndRejectFbInviteForSlotsResponseProto.AcceptAndRejectFbInviteForSlotsStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.AcceptAndRejectFbInviteForSlotsResponseProto.AcceptAndRejectFbInviteForSlotsStatus.SUCCESS)]
    public com.lvl6.proto.AcceptAndRejectFbInviteForSlotsResponseProto.AcceptAndRejectFbInviteForSlotsStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.UserFacebookInviteForSlotProto> _acceptedInvites = new global::System.Collections.Generic.List<com.lvl6.proto.UserFacebookInviteForSlotProto>();
    [global::ProtoBuf.ProtoMember(3, Name=@"acceptedInvites", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.UserFacebookInviteForSlotProto> acceptedInvites
    {
      get { return _acceptedInvites; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"AcceptAndRejectFbInviteForSlotsStatus")]
    public enum AcceptAndRejectFbInviteForSlotsStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_EXPIRED", Value=2)]
      FAIL_EXPIRED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_ALREADY_BEEN_USED", Value=3)]
      FAIL_ALREADY_BEEN_USED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=4)]
      FAIL_OTHER = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CombineUserMonsterPiecesRequestProto")]
  public partial class CombineUserMonsterPiecesRequestProto : global::ProtoBuf.IExtensible
  {
    public CombineUserMonsterPiecesRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _userMonsterIds = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"userMonsterIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> userMonsterIds
    {
      get { return _userMonsterIds; }
    }
  

    private int _gemCost = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gemCost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gemCost
    {
      get { return _gemCost; }
      set { _gemCost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CombineUserMonsterPiecesResponseProto")]
  public partial class CombineUserMonsterPiecesResponseProto : global::ProtoBuf.IExtensible
  {
    public CombineUserMonsterPiecesResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.CombineUserMonsterPiecesResponseProto.CombineUserMonsterPiecesStatus _status = com.lvl6.proto.CombineUserMonsterPiecesResponseProto.CombineUserMonsterPiecesStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.CombineUserMonsterPiecesResponseProto.CombineUserMonsterPiecesStatus.SUCCESS)]
    public com.lvl6.proto.CombineUserMonsterPiecesResponseProto.CombineUserMonsterPiecesStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"CombineUserMonsterPiecesStatus")]
    public enum CombineUserMonsterPiecesStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_INSUFFUCIENT_GEMS", Value=2)]
      FAIL_INSUFFUCIENT_GEMS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_MORE_THAN_ONE_MONSTER_FOR_SPEEDUP", Value=3)]
      FAIL_MORE_THAN_ONE_MONSTER_FOR_SPEEDUP = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=4)]
      FAIL_OTHER = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SellUserMonsterRequestProto")]
  public partial class SellUserMonsterRequestProto : global::ProtoBuf.IExtensible
  {
    public SellUserMonsterRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProtoWithMaxResources _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProtoWithMaxResources sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.MinimumUserMonsterSellProto> _sales = new global::System.Collections.Generic.List<com.lvl6.proto.MinimumUserMonsterSellProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"sales", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.MinimumUserMonsterSellProto> sales
    {
      get { return _sales; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SellUserMonsterResponseProto")]
  public partial class SellUserMonsterResponseProto : global::ProtoBuf.IExtensible
  {
    public SellUserMonsterResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProtoWithMaxResources _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProtoWithMaxResources sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.SellUserMonsterResponseProto.SellUserMonsterStatus _status = com.lvl6.proto.SellUserMonsterResponseProto.SellUserMonsterStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.SellUserMonsterResponseProto.SellUserMonsterStatus.SUCCESS)]
    public com.lvl6.proto.SellUserMonsterResponseProto.SellUserMonsterStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"SellUserMonsterStatus")]
    public enum SellUserMonsterStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=2)]
      FAIL_OTHER = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RestrictUserMonsterRequestProto")]
  public partial class RestrictUserMonsterRequestProto : global::ProtoBuf.IExtensible
  {
    public RestrictUserMonsterRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _userMonsterIds = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(3, Name=@"userMonsterIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> userMonsterIds
    {
      get { return _userMonsterIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RestrictUserMonsterResponseProto")]
  public partial class RestrictUserMonsterResponseProto : global::ProtoBuf.IExtensible
  {
    public RestrictUserMonsterResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.RestrictUserMonsterResponseProto.RestrictUserMonsterStatus _status = com.lvl6.proto.RestrictUserMonsterResponseProto.RestrictUserMonsterStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.RestrictUserMonsterResponseProto.RestrictUserMonsterStatus.SUCCESS)]
    public com.lvl6.proto.RestrictUserMonsterResponseProto.RestrictUserMonsterStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RestrictUserMonsterStatus")]
    public enum RestrictUserMonsterStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=2)]
      FAIL_OTHER = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}