//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EventUser.proto
// Note: requires additional types generated from: MonsterStuff.proto
// Note: requires additional types generated from: Structure.proto
// Note: requires additional types generated from: User.proto
namespace com.lvl6.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserCreateRequestProto")]
  public partial class UserCreateRequestProto : global::ProtoBuf.IExtensible
  {
    public UserCreateRequestProto() {}
    

    private string _udid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"udid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string udid
    {
      get { return _udid; }
      set { _udid = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _referrerCode = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"referrerCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string referrerCode
    {
      get { return _referrerCode; }
      set { _referrerCode = value; }
    }

    private string _deviceToken = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"deviceToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string deviceToken
    {
      get { return _deviceToken; }
      set { _deviceToken = value; }
    }

    private long _timeOfStructPurchase = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"timeOfStructPurchase", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timeOfStructPurchase
    {
      get { return _timeOfStructPurchase; }
      set { _timeOfStructPurchase = value; }
    }

    private long _timeOfStructBuild = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"timeOfStructBuild", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timeOfStructBuild
    {
      get { return _timeOfStructBuild; }
      set { _timeOfStructBuild = value; }
    }

    private com.lvl6.proto.CoordinateProto _structCoords = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"structCoords", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.CoordinateProto structCoords
    {
      get { return _structCoords; }
      set { _structCoords = value; }
    }

    private bool _usedDiamondsToBuilt = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"usedDiamondsToBuilt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool usedDiamondsToBuilt
    {
      get { return _usedDiamondsToBuilt; }
      set { _usedDiamondsToBuilt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserCreateResponseProto")]
  public partial class UserCreateResponseProto : global::ProtoBuf.IExtensible
  {
    public UserCreateResponseProto() {}
    

    private com.lvl6.proto.FullUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.FullUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.UserCreateResponseProto.UserCreateStatus _status = com.lvl6.proto.UserCreateResponseProto.UserCreateStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.UserCreateResponseProto.UserCreateStatus.SUCCESS)]
    public com.lvl6.proto.UserCreateResponseProto.UserCreateStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"UserCreateStatus")]
    public enum UserCreateStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_NAME", Value=2)]
      INVALID_NAME = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_WITH_UDID_ALREADY_EXISTS", Value=3)]
      USER_WITH_UDID_ALREADY_EXISTS = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_REFER_CODE", Value=4)]
      INVALID_REFER_CODE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER_FAIL", Value=5)]
      OTHER_FAIL = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LevelUpRequestProto")]
  public partial class LevelUpRequestProto : global::ProtoBuf.IExtensible
  {
    public LevelUpRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LevelUpResponseProto")]
  public partial class LevelUpResponseProto : global::ProtoBuf.IExtensible
  {
    public LevelUpResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.LevelUpResponseProto.LevelUpStatus _status = com.lvl6.proto.LevelUpResponseProto.LevelUpStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.LevelUpResponseProto.LevelUpStatus.SUCCESS)]
    public com.lvl6.proto.LevelUpResponseProto.LevelUpStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"LevelUpStatus")]
    public enum LevelUpStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_EXP_TO_NEXT_LEVEL", Value=2)]
      NOT_ENOUGH_EXP_TO_NEXT_LEVEL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALREADY_AT_MAX_LEVEL", Value=3)]
      ALREADY_AT_MAX_LEVEL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER_FAIL", Value=4)]
      OTHER_FAIL = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetrieveUsersForUserIdsRequestProto")]
  public partial class RetrieveUsersForUserIdsRequestProto : global::ProtoBuf.IExtensible
  {
    public RetrieveUsersForUserIdsRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _requestedUserIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"requestedUserIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> requestedUserIds
    {
      get { return _requestedUserIds; }
    }
  

    private bool _includeCurMonsterTeam = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"includeCurMonsterTeam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool includeCurMonsterTeam
    {
      get { return _includeCurMonsterTeam; }
      set { _includeCurMonsterTeam = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RetrieveUsersForUserIdsResponseProto")]
  public partial class RetrieveUsersForUserIdsResponseProto : global::ProtoBuf.IExtensible
  {
    public RetrieveUsersForUserIdsResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.FullUserProto> _requestedUsers = new global::System.Collections.Generic.List<com.lvl6.proto.FullUserProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"requestedUsers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.FullUserProto> requestedUsers
    {
      get { return _requestedUsers; }
    }
  
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.UserCurrentMonsterTeamProto> _curTeam = new global::System.Collections.Generic.List<com.lvl6.proto.UserCurrentMonsterTeamProto>();
    [global::ProtoBuf.ProtoMember(3, Name=@"curTeam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.UserCurrentMonsterTeamProto> curTeam
    {
      get { return _curTeam; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogoutRequestProto")]
  public partial class LogoutRequestProto : global::ProtoBuf.IExtensible
  {
    public LogoutRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateClientUserResponseProto")]
  public partial class UpdateClientUserResponseProto : global::ProtoBuf.IExtensible
  {
    public UpdateClientUserResponseProto() {}
    

    private com.lvl6.proto.FullUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.FullUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private long _timeOfUserUpdate = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"timeOfUserUpdate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timeOfUserUpdate
    {
      get { return _timeOfUserUpdate; }
      set { _timeOfUserUpdate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}