//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EventMiniJob.proto
// Note: requires additional types generated from: MiniJobConfig.proto
// Note: requires additional types generated from: MonsterStuff.proto
// Note: requires additional types generated from: User.proto
namespace com.lvl6.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpawnMiniJobRequestProto")]
  public partial class SpawnMiniJobRequestProto : global::ProtoBuf.IExtensible
  {
    public SpawnMiniJobRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private long _clientTime = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"clientTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long clientTime
    {
      get { return _clientTime; }
      set { _clientTime = value; }
    }

    private int _numToSpawn = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"numToSpawn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numToSpawn
    {
      get { return _numToSpawn; }
      set { _numToSpawn = value; }
    }

    private int _structId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"structId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int structId
    {
      get { return _structId; }
      set { _structId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpawnMiniJobResponseProto")]
  public partial class SpawnMiniJobResponseProto : global::ProtoBuf.IExtensible
  {
    public SpawnMiniJobResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.UserMiniJobProto> _miniJobs = new global::System.Collections.Generic.List<com.lvl6.proto.UserMiniJobProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"miniJobs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.UserMiniJobProto> miniJobs
    {
      get { return _miniJobs; }
    }
  

    private com.lvl6.proto.SpawnMiniJobResponseProto.SpawnMiniJobStatus _status = com.lvl6.proto.SpawnMiniJobResponseProto.SpawnMiniJobStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.SpawnMiniJobResponseProto.SpawnMiniJobStatus.SUCCESS)]
    public com.lvl6.proto.SpawnMiniJobResponseProto.SpawnMiniJobStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"SpawnMiniJobStatus")]
    public enum SpawnMiniJobStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=2)]
      FAIL_OTHER = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BeginMiniJobRequestProto")]
  public partial class BeginMiniJobRequestProto : global::ProtoBuf.IExtensible
  {
    public BeginMiniJobRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private long _clientTime = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"clientTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long clientTime
    {
      get { return _clientTime; }
      set { _clientTime = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _userMonsterIds = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(3, Name=@"userMonsterIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> userMonsterIds
    {
      get { return _userMonsterIds; }
    }
  

    private long _userMiniJobId = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"userMiniJobId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userMiniJobId
    {
      get { return _userMiniJobId; }
      set { _userMiniJobId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BeginMiniJobResponseProto")]
  public partial class BeginMiniJobResponseProto : global::ProtoBuf.IExtensible
  {
    public BeginMiniJobResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.BeginMiniJobResponseProto.BeginMiniJobStatus _status = com.lvl6.proto.BeginMiniJobResponseProto.BeginMiniJobStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.BeginMiniJobResponseProto.BeginMiniJobStatus.SUCCESS)]
    public com.lvl6.proto.BeginMiniJobResponseProto.BeginMiniJobStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"BeginMiniJobStatus")]
    public enum BeginMiniJobStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=2)]
      FAIL_OTHER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_NO_MINI_JOB_EXISTS", Value=3)]
      FAIL_NO_MINI_JOB_EXISTS = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CompleteMiniJobRequestProto")]
  public partial class CompleteMiniJobRequestProto : global::ProtoBuf.IExtensible
  {
    public CompleteMiniJobRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private long _clientTime = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"clientTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long clientTime
    {
      get { return _clientTime; }
      set { _clientTime = value; }
    }

    private long _userMiniJobId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userMiniJobId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userMiniJobId
    {
      get { return _userMiniJobId; }
      set { _userMiniJobId = value; }
    }

    private bool _isSpeedUp = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isSpeedUp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isSpeedUp
    {
      get { return _isSpeedUp; }
      set { _isSpeedUp = value; }
    }

    private int _gemCost = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gemCost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gemCost
    {
      get { return _gemCost; }
      set { _gemCost = value; }
    }
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterCurrentHealthProto> _umchp = new global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterCurrentHealthProto>();
    [global::ProtoBuf.ProtoMember(6, Name=@"umchp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.UserMonsterCurrentHealthProto> umchp
    {
      get { return _umchp; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CompleteMiniJobResponseProto")]
  public partial class CompleteMiniJobResponseProto : global::ProtoBuf.IExtensible
  {
    public CompleteMiniJobResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.CompleteMiniJobResponseProto.CompleteMiniJobStatus _status = com.lvl6.proto.CompleteMiniJobResponseProto.CompleteMiniJobStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.CompleteMiniJobResponseProto.CompleteMiniJobStatus.SUCCESS)]
    public com.lvl6.proto.CompleteMiniJobResponseProto.CompleteMiniJobStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"CompleteMiniJobStatus")]
    public enum CompleteMiniJobStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=2)]
      FAIL_OTHER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_INSUFFICIENT_GEMS", Value=3)]
      FAIL_INSUFFICIENT_GEMS = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_NO_MINI_JOB_EXISTS", Value=4)]
      FAIL_NO_MINI_JOB_EXISTS = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RedeemMiniJobRequestProto")]
  public partial class RedeemMiniJobRequestProto : global::ProtoBuf.IExtensible
  {
    public RedeemMiniJobRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProtoWithMaxResources _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProtoWithMaxResources sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private long _clientTime = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"clientTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long clientTime
    {
      get { return _clientTime; }
      set { _clientTime = value; }
    }

    private long _userMiniJobId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userMiniJobId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userMiniJobId
    {
      get { return _userMiniJobId; }
      set { _userMiniJobId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RedeemMiniJobResponseProto")]
  public partial class RedeemMiniJobResponseProto : global::ProtoBuf.IExtensible
  {
    public RedeemMiniJobResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProtoWithMaxResources _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProtoWithMaxResources sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.FullUserMonsterProto _fump = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fump", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.FullUserMonsterProto fump
    {
      get { return _fump; }
      set { _fump = value; }
    }

    private com.lvl6.proto.RedeemMiniJobResponseProto.RedeemMiniJobStatus _status = com.lvl6.proto.RedeemMiniJobResponseProto.RedeemMiniJobStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.RedeemMiniJobResponseProto.RedeemMiniJobStatus.SUCCESS)]
    public com.lvl6.proto.RedeemMiniJobResponseProto.RedeemMiniJobStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RedeemMiniJobStatus")]
    public enum RedeemMiniJobStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=2)]
      FAIL_OTHER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_NO_MINI_JOB_EXISTS", Value=3)]
      FAIL_NO_MINI_JOB_EXISTS = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_MINI_JOB_INCOMPLETE", Value=4)]
      FAIL_MINI_JOB_INCOMPLETE = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}