//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EventItem.proto
// Note: requires additional types generated from: MonsterStuff.proto
// Note: requires additional types generated from: User.proto
namespace com.lvl6.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TradeItemForBoosterRequestProto")]
  public partial class TradeItemForBoosterRequestProto : global::ProtoBuf.IExtensible
  {
    public TradeItemForBoosterRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private int _itemId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }

    private long _clientTime = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"clientTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long clientTime
    {
      get { return _clientTime; }
      set { _clientTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TradeItemForBoosterResponseProto")]
  public partial class TradeItemForBoosterResponseProto : global::ProtoBuf.IExtensible
  {
    public TradeItemForBoosterResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private com.lvl6.proto.TradeItemForBoosterResponseProto.TradeItemForBoosterStatus _status = com.lvl6.proto.TradeItemForBoosterResponseProto.TradeItemForBoosterStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.TradeItemForBoosterResponseProto.TradeItemForBoosterStatus.SUCCESS)]
    public com.lvl6.proto.TradeItemForBoosterResponseProto.TradeItemForBoosterStatus status
    {
      get { return _status; }
      set { _status = value; }
    }

    private com.lvl6.proto.FullUserMonsterProto _fump = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fump", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.FullUserMonsterProto fump
    {
      get { return _fump; }
      set { _fump = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"TradeItemForBoosterStatus")]
    public enum TradeItemForBoosterStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=2)]
      FAIL_OTHER = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}