//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EventPvp.proto
// Note: requires additional types generated from: Battle.proto
// Note: requires additional types generated from: User.proto
namespace com.lvl6.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueueUpRequestProto")]
  public partial class QueueUpRequestProto : global::ProtoBuf.IExtensible
  {
    public QueueUpRequestProto() {}
    

    private com.lvl6.proto.MinimumUserProto _attacker = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"attacker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto attacker
    {
      get { return _attacker; }
      set { _attacker = value; }
    }

    private int _attackerElo = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"attackerElo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attackerElo
    {
      get { return _attackerElo; }
      set { _attackerElo = value; }
    }

    private int _gemsSpent = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gemsSpent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gemsSpent
    {
      get { return _gemsSpent; }
      set { _gemsSpent = value; }
    }

    private int _cashChange = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cashChange", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cashChange
    {
      get { return _cashChange; }
      set { _cashChange = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _seenUserIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"seenUserIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> seenUserIds
    {
      get { return _seenUserIds; }
    }
  

    private long _clientTime = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"clientTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long clientTime
    {
      get { return _clientTime; }
      set { _clientTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueueUpResponseProto")]
  public partial class QueueUpResponseProto : global::ProtoBuf.IExtensible
  {
    public QueueUpResponseProto() {}
    

    private com.lvl6.proto.MinimumUserProto _attacker = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"attacker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto attacker
    {
      get { return _attacker; }
      set { _attacker = value; }
    }

    private com.lvl6.proto.PvpProto _defenderInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"defenderInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.PvpProto defenderInfo
    {
      get { return _defenderInfo; }
      set { _defenderInfo = value; }
    }

    private com.lvl6.proto.QueueUpResponseProto.QueueUpStatus _status = com.lvl6.proto.QueueUpResponseProto.QueueUpStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.QueueUpResponseProto.QueueUpStatus.SUCCESS)]
    public com.lvl6.proto.QueueUpResponseProto.QueueUpStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"QueueUpStatus")]
    public enum QueueUpStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_NOT_ENOUGH_CASH", Value=2)]
      FAIL_NOT_ENOUGH_CASH = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=3)]
      FAIL_OTHER = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}