//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Quest.proto
// Note: requires additional types generated from: Job.proto
namespace com.lvl6.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FullQuestProto")]
  public partial class FullQuestProto : global::ProtoBuf.IExtensible
  {
    public FullQuestProto() {}
    

    private int _questId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"questId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int questId
    {
      get { return _questId; }
      set { _questId = value; }
    }

    private int _cityId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cityId
    {
      get { return _cityId; }
      set { _cityId = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _description = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }

    private string _doneResponse = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"doneResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string doneResponse
    {
      get { return _doneResponse; }
      set { _doneResponse = value; }
    }

    private com.lvl6.proto.DialogueProto _acceptDialogue = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"acceptDialogue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.DialogueProto acceptDialogue
    {
      get { return _acceptDialogue; }
      set { _acceptDialogue = value; }
    }

    private int _assetNumWithinCity = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"assetNumWithinCity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int assetNumWithinCity
    {
      get { return _assetNumWithinCity; }
      set { _assetNumWithinCity = value; }
    }

    private int _coinsGained = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"coinsGained", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int coinsGained
    {
      get { return _coinsGained; }
      set { _coinsGained = value; }
    }

    private int _diamondsGained = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"diamondsGained", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamondsGained
    {
      get { return _diamondsGained; }
      set { _diamondsGained = value; }
    }

    private int _expGained = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"expGained", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int expGained
    {
      get { return _expGained; }
      set { _expGained = value; }
    }

    private int _monsterId = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"monsterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int monsterId
    {
      get { return _monsterId; }
      set { _monsterId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _questsRequiredForThis = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"questsRequiredForThis", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> questsRequiredForThis
    {
      get { return _questsRequiredForThis; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _taskReqs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(13, Name=@"taskReqs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> taskReqs
    {
      get { return _taskReqs; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _upgradeStructJobsReqs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(14, Name=@"upgradeStructJobsReqs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> upgradeStructJobsReqs
    {
      get { return _upgradeStructJobsReqs; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _buildStructJobsReqs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(15, Name=@"buildStructJobsReqs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> buildStructJobsReqs
    {
      get { return _buildStructJobsReqs; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _monsterJobsReqs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(16, Name=@"monsterJobsReqs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> monsterJobsReqs
    {
      get { return _monsterJobsReqs; }
    }
  

    private int _coinRetrievalReq = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"coinRetrievalReq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int coinRetrievalReq
    {
      get { return _coinRetrievalReq; }
      set { _coinRetrievalReq = value; }
    }

    private com.lvl6.proto.SpecialQuestAction _specialQuestActionReq = com.lvl6.proto.SpecialQuestAction.REQUEST_JOIN_CLAN;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"specialQuestActionReq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.SpecialQuestAction.REQUEST_JOIN_CLAN)]
    public com.lvl6.proto.SpecialQuestAction specialQuestActionReq
    {
      get { return _specialQuestActionReq; }
      set { _specialQuestActionReq = value; }
    }

    private int _numComponentsForGood = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"numComponentsForGood", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numComponentsForGood
    {
      get { return _numComponentsForGood; }
      set { _numComponentsForGood = value; }
    }

    private string _questGiverName = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"questGiverName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string questGiverName
    {
      get { return _questGiverName; }
      set { _questGiverName = value; }
    }

    private string _questGiverImageSuffix = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"questGiverImageSuffix", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string questGiverImageSuffix
    {
      get { return _questGiverImageSuffix; }
      set { _questGiverImageSuffix = value; }
    }

    private int _priority = default(int);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"priority", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int priority
    {
      get { return _priority; }
      set { _priority = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DialogueProto")]
  public partial class DialogueProto : global::ProtoBuf.IExtensible
  {
    public DialogueProto() {}
    
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.DialogueProto.SpeechSegmentProto> _speechSegment = new global::System.Collections.Generic.List<com.lvl6.proto.DialogueProto.SpeechSegmentProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"speechSegment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.DialogueProto.SpeechSegmentProto> speechSegment
    {
      get { return _speechSegment; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpeechSegmentProto")]
  public partial class SpeechSegmentProto : global::ProtoBuf.IExtensible
  {
    public SpeechSegmentProto() {}
    

    private com.lvl6.proto.DialogueProto.SpeechSegmentProto.DialogueSpeaker _speaker = com.lvl6.proto.DialogueProto.SpeechSegmentProto.DialogueSpeaker.PLAYER_TYPE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"speaker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.DialogueProto.SpeechSegmentProto.DialogueSpeaker.PLAYER_TYPE)]
    public com.lvl6.proto.DialogueProto.SpeechSegmentProto.DialogueSpeaker speaker
    {
      get { return _speaker; }
      set { _speaker = value; }
    }

    private string _speakerText = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"speakerText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string speakerText
    {
      get { return _speakerText; }
      set { _speakerText = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"DialogueSpeaker")]
    public enum DialogueSpeaker
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_TYPE", Value=1)]
      PLAYER_TYPE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TUTORIAL_GIRL", Value=2)]
      TUTORIAL_GIRL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUESTGIVER_1", Value=3)]
      QUESTGIVER_1 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUESTGIVER_2", Value=4)]
      QUESTGIVER_2 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUESTGIVER_3", Value=5)]
      QUESTGIVER_3 = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUESTGIVER_4", Value=6)]
      QUESTGIVER_4 = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUESTGIVER_5", Value=7)]
      QUESTGIVER_5 = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FullUserQuestDataLargeProto")]
  public partial class FullUserQuestDataLargeProto : global::ProtoBuf.IExtensible
  {
    public FullUserQuestDataLargeProto() {}
    

    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private int _questId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"questId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int questId
    {
      get { return _questId; }
      set { _questId = value; }
    }

    private bool _isRedeemed = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isRedeemed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isRedeemed
    {
      get { return _isRedeemed; }
      set { _isRedeemed = value; }
    }

    private bool _isComplete = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isComplete", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isComplete
    {
      get { return _isComplete; }
      set { _isComplete = value; }
    }
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.MinimumUserBuildStructJobProto> _requiredBuildStructJobProgress = new global::System.Collections.Generic.List<com.lvl6.proto.MinimumUserBuildStructJobProto>();
    [global::ProtoBuf.ProtoMember(5, Name=@"requiredBuildStructJobProgress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.MinimumUserBuildStructJobProto> requiredBuildStructJobProgress
    {
      get { return _requiredBuildStructJobProgress; }
    }
  
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.MinimumUserUpgradeStructJobProto> _requiredUpgradeStructJobProgress = new global::System.Collections.Generic.List<com.lvl6.proto.MinimumUserUpgradeStructJobProto>();
    [global::ProtoBuf.ProtoMember(6, Name=@"requiredUpgradeStructJobProgress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.MinimumUserUpgradeStructJobProto> requiredUpgradeStructJobProgress
    {
      get { return _requiredUpgradeStructJobProgress; }
    }
  
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.MinimumUserQuestTaskProto> _requiredTasksProgress = new global::System.Collections.Generic.List<com.lvl6.proto.MinimumUserQuestTaskProto>();
    [global::ProtoBuf.ProtoMember(7, Name=@"requiredTasksProgress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.MinimumUserQuestTaskProto> requiredTasksProgress
    {
      get { return _requiredTasksProgress; }
    }
  

    private int _coinsRetrievedForReq = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"coinsRetrievedForReq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int coinsRetrievedForReq
    {
      get { return _coinsRetrievedForReq; }
      set { _coinsRetrievedForReq = value; }
    }

    private int _numComponentsComplete = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"numComponentsComplete", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numComponentsComplete
    {
      get { return _numComponentsComplete; }
      set { _numComponentsComplete = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MinimumUserQuestTaskProto")]
  public partial class MinimumUserQuestTaskProto : global::ProtoBuf.IExtensible
  {
    public MinimumUserQuestTaskProto() {}
    

    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private int _questId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"questId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int questId
    {
      get { return _questId; }
      set { _questId = value; }
    }

    private int _taskId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"taskId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int taskId
    {
      get { return _taskId; }
      set { _taskId = value; }
    }

    private int _numTimesActed = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"numTimesActed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numTimesActed
    {
      get { return _numTimesActed; }
      set { _numTimesActed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"SpecialQuestAction")]
    public enum SpecialQuestAction
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQUEST_JOIN_CLAN", Value=1)]
      REQUEST_JOIN_CLAN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVOLVE_A_MONSTER", Value=2)]
      EVOLVE_A_MONSTER = 2
    }
  
}