//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SharedEnumConfig.proto
namespace com.lvl6.proto
{
    [global::ProtoBuf.ProtoContract(Name=@"DayOfWeek")]
    public enum DayOfWeek
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUNDAY", Value=1)]
      SUNDAY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MONDAY", Value=2)]
      MONDAY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TUESDAY", Value=3)]
      TUESDAY = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WEDNESDAY", Value=4)]
      WEDNESDAY = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THURSDAY", Value=5)]
      THURSDAY = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRIDAY", Value=6)]
      FRIDAY = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SATURDAY", Value=7)]
      SATURDAY = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_DAY_OF_WEEK", Value=8)]
      NO_DAY_OF_WEEK = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Element")]
    public enum Element
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_ELEMENT", Value=1)]
      NO_ELEMENT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIRE", Value=2)]
      FIRE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EARTH", Value=3)]
      EARTH = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WATER", Value=4)]
      WATER = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LIGHT", Value=5)]
      LIGHT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DARK", Value=6)]
      DARK = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROCK", Value=7)]
      ROCK = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Quality")]
    public enum Quality
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_QUALITY", Value=1)]
      NO_QUALITY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMMON", Value=2)]
      COMMON = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RARE", Value=3)]
      RARE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ULTRA", Value=4)]
      ULTRA = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EPIC", Value=5)]
      EPIC = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEGENDARY", Value=6)]
      LEGENDARY = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVO", Value=7)]
      EVO = 7
    }
  
}