//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: StaticData.proto
// Note: requires additional types generated from: City.proto
// Note: requires additional types generated from: MonsterStuff.proto
// Note: requires additional types generated from: Quest.proto
// Note: requires additional types generated from: Structure.proto
// Note: requires additional types generated from: Task.proto
// Note: requires additional types generated from: User.proto
namespace com.lvl6.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StaticDataProto")]
  public partial class StaticDataProto : global::ProtoBuf.IExtensible
  {
    public StaticDataProto() {}
    

    private com.lvl6.proto.MinimumUserProto _sender = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.CityExpansionCostProto> _expansionCosts = new global::System.Collections.Generic.List<com.lvl6.proto.CityExpansionCostProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"expansionCosts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.CityExpansionCostProto> expansionCosts
    {
      get { return _expansionCosts; }
    }
  
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.FullCityProto> _allCities = new global::System.Collections.Generic.List<com.lvl6.proto.FullCityProto>();
    [global::ProtoBuf.ProtoMember(3, Name=@"allCities", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.FullCityProto> allCities
    {
      get { return _allCities; }
    }
  
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.FullStructureProto> _allStructs = new global::System.Collections.Generic.List<com.lvl6.proto.FullStructureProto>();
    [global::ProtoBuf.ProtoMember(4, Name=@"allStructs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.FullStructureProto> allStructs
    {
      get { return _allStructs; }
    }
  
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.FullTaskProto> _allTasks = new global::System.Collections.Generic.List<com.lvl6.proto.FullTaskProto>();
    [global::ProtoBuf.ProtoMember(5, Name=@"allTasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.FullTaskProto> allTasks
    {
      get { return _allTasks; }
    }
  
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.MonsterProto> _allMonsters = new global::System.Collections.Generic.List<com.lvl6.proto.MonsterProto>();
    [global::ProtoBuf.ProtoMember(6, Name=@"allMonsters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.MonsterProto> allMonsters
    {
      get { return _allMonsters; }
    }
  
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.StaticUserLevelInfoProto> _slip = new global::System.Collections.Generic.List<com.lvl6.proto.StaticUserLevelInfoProto>();
    [global::ProtoBuf.ProtoMember(7, Name=@"slip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.StaticUserLevelInfoProto> slip
    {
      get { return _slip; }
    }
  
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.FullQuestProto> _inProgressQuests = new global::System.Collections.Generic.List<com.lvl6.proto.FullQuestProto>();
    [global::ProtoBuf.ProtoMember(8, Name=@"inProgressQuests", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.FullQuestProto> inProgressQuests
    {
      get { return _inProgressQuests; }
    }
  
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.FullQuestProto> _unredeemedQuests = new global::System.Collections.Generic.List<com.lvl6.proto.FullQuestProto>();
    [global::ProtoBuf.ProtoMember(9, Name=@"unredeemedQuests", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.FullQuestProto> unredeemedQuests
    {
      get { return _unredeemedQuests; }
    }
  
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.FullQuestProto> _availableQuests = new global::System.Collections.Generic.List<com.lvl6.proto.FullQuestProto>();
    [global::ProtoBuf.ProtoMember(10, Name=@"availableQuests", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.FullQuestProto> availableQuests
    {
      get { return _availableQuests; }
    }
  

    private com.lvl6.proto.StaticDataProto.RetrieveStaticDataStatus _status = com.lvl6.proto.StaticDataProto.RetrieveStaticDataStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.StaticDataProto.RetrieveStaticDataStatus.SUCCESS)]
    public com.lvl6.proto.StaticDataProto.RetrieveStaticDataStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RetrieveStaticDataStatus")]
    public enum RetrieveStaticDataStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOME_FAIL", Value=2)]
      SOME_FAIL = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}