//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Structure.proto
namespace com.lvl6.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FullStructureProto")]
  public partial class FullStructureProto : global::ProtoBuf.IExtensible
  {
    public FullStructureProto() {}
    

    private int _structId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"structId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int structId
    {
      get { return _structId; }
      set { _structId = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }

    private int _income = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"income", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int income
    {
      get { return _income; }
      set { _income = value; }
    }

    private int _minutesToGain = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"minutesToGain", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minutesToGain
    {
      get { return _minutesToGain; }
      set { _minutesToGain = value; }
    }

    private int _minutesToBuild = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"minutesToBuild", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minutesToBuild
    {
      get { return _minutesToBuild; }
      set { _minutesToBuild = value; }
    }

    private int _buildPrice = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"buildPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buildPrice
    {
      get { return _buildPrice; }
      set { _buildPrice = value; }
    }

    private bool _isPremiumCurrency = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"isPremiumCurrency", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isPremiumCurrency
    {
      get { return _isPremiumCurrency; }
      set { _isPremiumCurrency = value; }
    }

    private int _sellPrice = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sellPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sellPrice
    {
      get { return _sellPrice; }
      set { _sellPrice = value; }
    }

    private int _minLevel = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"minLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minLevel
    {
      get { return _minLevel; }
      set { _minLevel = value; }
    }

    private int _xLength = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"xLength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int xLength
    {
      get { return _xLength; }
      set { _xLength = value; }
    }

    private int _yLength = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"yLength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int yLength
    {
      get { return _yLength; }
      set { _yLength = value; }
    }

    private int _imgVerticalPixelOffset = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"imgVerticalPixelOffset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int imgVerticalPixelOffset
    {
      get { return _imgVerticalPixelOffset; }
      set { _imgVerticalPixelOffset = value; }
    }

    private int _successorStructId = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"successorStructId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int successorStructId
    {
      get { return _successorStructId; }
      set { _successorStructId = value; }
    }

    private int _predecessorStructId = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"predecessorStructId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int predecessorStructId
    {
      get { return _predecessorStructId; }
      set { _predecessorStructId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FullUserStructureProto")]
  public partial class FullUserStructureProto : global::ProtoBuf.IExtensible
  {
    public FullUserStructureProto() {}
    

    private int _userStructId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userStructId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userStructId
    {
      get { return _userStructId; }
      set { _userStructId = value; }
    }

    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private int _structId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"structId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int structId
    {
      get { return _structId; }
      set { _structId = value; }
    }

    private long _lastRetrieved = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lastRetrieved", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lastRetrieved
    {
      get { return _lastRetrieved; }
      set { _lastRetrieved = value; }
    }

    private com.lvl6.proto.CoordinateProto _coordinates = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"coordinates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.CoordinateProto coordinates
    {
      get { return _coordinates; }
      set { _coordinates = value; }
    }

    private long _purchaseTime = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"purchaseTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long purchaseTime
    {
      get { return _purchaseTime; }
      set { _purchaseTime = value; }
    }

    private bool _isComplete = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"isComplete", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isComplete
    {
      get { return _isComplete; }
      set { _isComplete = value; }
    }

    private com.lvl6.proto.StructOrientation _orientation = com.lvl6.proto.StructOrientation.POSITION_1;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"orientation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.StructOrientation.POSITION_1)]
    public com.lvl6.proto.StructOrientation orientation
    {
      get { return _orientation; }
      set { _orientation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoordinateProto")]
  public partial class CoordinateProto : global::ProtoBuf.IExtensible
  {
    public CoordinateProto() {}
    

    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }

    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"StructOrientation")]
    public enum StructOrientation
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"POSITION_1", Value=1)]
      POSITION_1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"POSITION_2", Value=2)]
      POSITION_2 = 2
    }
  
}