//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Structure.proto
namespace com.lvl6.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StructureInfoProto")]
  public partial class StructureInfoProto : global::ProtoBuf.IExtensible
  {
    public StructureInfoProto() {}
    

    private int _structId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"structId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int structId
    {
      get { return _structId; }
      set { _structId = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }

    private com.lvl6.proto.StructureInfoProto.StructType _structType = com.lvl6.proto.StructureInfoProto.StructType.NO_STRUCT;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"structType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.StructureInfoProto.StructType.NO_STRUCT)]
    public com.lvl6.proto.StructureInfoProto.StructType structType
    {
      get { return _structType; }
      set { _structType = value; }
    }

    private com.lvl6.proto.ResourceType _buildResourceType = com.lvl6.proto.ResourceType.NO_RESOURCE;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"buildResourceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.ResourceType.NO_RESOURCE)]
    public com.lvl6.proto.ResourceType buildResourceType
    {
      get { return _buildResourceType; }
      set { _buildResourceType = value; }
    }

    private int _buildCost = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"buildCost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buildCost
    {
      get { return _buildCost; }
      set { _buildCost = value; }
    }

    private int _minutesToBuild = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"minutesToBuild", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minutesToBuild
    {
      get { return _minutesToBuild; }
      set { _minutesToBuild = value; }
    }

    private int _prerequisiteTownHallLvl = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"prerequisiteTownHallLvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int prerequisiteTownHallLvl
    {
      get { return _prerequisiteTownHallLvl; }
      set { _prerequisiteTownHallLvl = value; }
    }

    private int _width = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int width
    {
      get { return _width; }
      set { _width = value; }
    }

    private int _height = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }

    private int _predecessorStructId = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"predecessorStructId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int predecessorStructId
    {
      get { return _predecessorStructId; }
      set { _predecessorStructId = value; }
    }

    private int _successorStructId = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"successorStructId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int successorStructId
    {
      get { return _successorStructId; }
      set { _successorStructId = value; }
    }

    private string _imgName = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"imgName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string imgName
    {
      get { return _imgName; }
      set { _imgName = value; }
    }

    private float _imgVerticalPixelOffset = default(float);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"imgVerticalPixelOffset", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float imgVerticalPixelOffset
    {
      get { return _imgVerticalPixelOffset; }
      set { _imgVerticalPixelOffset = value; }
    }

    private float _imgHorizontalPixelOffset = default(float);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"imgHorizontalPixelOffset", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float imgHorizontalPixelOffset
    {
      get { return _imgHorizontalPixelOffset; }
      set { _imgHorizontalPixelOffset = value; }
    }

    private string _description = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }

    private string _shortDescription = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"shortDescription", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string shortDescription
    {
      get { return _shortDescription; }
      set { _shortDescription = value; }
    }

    private string _shadowImgName = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"shadowImgName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string shadowImgName
    {
      get { return _shadowImgName; }
      set { _shadowImgName = value; }
    }

    private float _shadowVerticalOffset = default(float);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"shadowVerticalOffset", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float shadowVerticalOffset
    {
      get { return _shadowVerticalOffset; }
      set { _shadowVerticalOffset = value; }
    }

    private float _shadowHorizontalOfffset = default(float);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"shadowHorizontalOfffset", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float shadowHorizontalOfffset
    {
      get { return _shadowHorizontalOfffset; }
      set { _shadowHorizontalOfffset = value; }
    }

    private float _shadowScale = default(float);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"shadowScale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float shadowScale
    {
      get { return _shadowScale; }
      set { _shadowScale = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"StructType")]
    public enum StructType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_STRUCT", Value=8)]
      NO_STRUCT = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESOURCE_GENERATOR", Value=1)]
      RESOURCE_GENERATOR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESOURCE_STORAGE", Value=2)]
      RESOURCE_STORAGE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HOSPITAL", Value=3)]
      HOSPITAL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESIDENCE", Value=4)]
      RESIDENCE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOWN_HALL", Value=5)]
      TOWN_HALL = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LAB", Value=6)]
      LAB = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVO", Value=7)]
      EVO = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceGeneratorProto")]
  public partial class ResourceGeneratorProto : global::ProtoBuf.IExtensible
  {
    public ResourceGeneratorProto() {}
    

    private com.lvl6.proto.StructureInfoProto _structInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"structInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.StructureInfoProto structInfo
    {
      get { return _structInfo; }
      set { _structInfo = value; }
    }

    private com.lvl6.proto.ResourceType _resourceType = com.lvl6.proto.ResourceType.NO_RESOURCE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resourceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.ResourceType.NO_RESOURCE)]
    public com.lvl6.proto.ResourceType resourceType
    {
      get { return _resourceType; }
      set { _resourceType = value; }
    }

    private float _productionRate = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"productionRate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float productionRate
    {
      get { return _productionRate; }
      set { _productionRate = value; }
    }

    private int _capacity = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"capacity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int capacity
    {
      get { return _capacity; }
      set { _capacity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceStorageProto")]
  public partial class ResourceStorageProto : global::ProtoBuf.IExtensible
  {
    public ResourceStorageProto() {}
    

    private com.lvl6.proto.StructureInfoProto _structInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"structInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.StructureInfoProto structInfo
    {
      get { return _structInfo; }
      set { _structInfo = value; }
    }

    private com.lvl6.proto.ResourceType _resourceType = com.lvl6.proto.ResourceType.NO_RESOURCE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resourceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.ResourceType.NO_RESOURCE)]
    public com.lvl6.proto.ResourceType resourceType
    {
      get { return _resourceType; }
      set { _resourceType = value; }
    }

    private int _capacity = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"capacity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int capacity
    {
      get { return _capacity; }
      set { _capacity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HospitalProto")]
  public partial class HospitalProto : global::ProtoBuf.IExtensible
  {
    public HospitalProto() {}
    

    private com.lvl6.proto.StructureInfoProto _structInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"structInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.StructureInfoProto structInfo
    {
      get { return _structInfo; }
      set { _structInfo = value; }
    }

    private int _queueSize = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"queueSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int queueSize
    {
      get { return _queueSize; }
      set { _queueSize = value; }
    }

    private float _healthPerSecond = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"healthPerSecond", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float healthPerSecond
    {
      get { return _healthPerSecond; }
      set { _healthPerSecond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LabProto")]
  public partial class LabProto : global::ProtoBuf.IExtensible
  {
    public LabProto() {}
    

    private com.lvl6.proto.StructureInfoProto _structInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"structInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.StructureInfoProto structInfo
    {
      get { return _structInfo; }
      set { _structInfo = value; }
    }

    private int _queueSize = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"queueSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int queueSize
    {
      get { return _queueSize; }
      set { _queueSize = value; }
    }

    private float _pointsPerSecond = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pointsPerSecond", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float pointsPerSecond
    {
      get { return _pointsPerSecond; }
      set { _pointsPerSecond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResidenceProto")]
  public partial class ResidenceProto : global::ProtoBuf.IExtensible
  {
    public ResidenceProto() {}
    

    private com.lvl6.proto.StructureInfoProto _structInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"structInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.StructureInfoProto structInfo
    {
      get { return _structInfo; }
      set { _structInfo = value; }
    }

    private int _numMonsterSlots = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"numMonsterSlots", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numMonsterSlots
    {
      get { return _numMonsterSlots; }
      set { _numMonsterSlots = value; }
    }

    private int _numBonusMonsterSlots = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"numBonusMonsterSlots", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numBonusMonsterSlots
    {
      get { return _numBonusMonsterSlots; }
      set { _numBonusMonsterSlots = value; }
    }

    private int _numGemsRequired = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"numGemsRequired", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numGemsRequired
    {
      get { return _numGemsRequired; }
      set { _numGemsRequired = value; }
    }

    private int _numAcceptedFbInvites = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"numAcceptedFbInvites", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numAcceptedFbInvites
    {
      get { return _numAcceptedFbInvites; }
      set { _numAcceptedFbInvites = value; }
    }

    private string _occupationName = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"occupationName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string occupationName
    {
      get { return _occupationName; }
      set { _occupationName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TownHallProto")]
  public partial class TownHallProto : global::ProtoBuf.IExtensible
  {
    public TownHallProto() {}
    

    private com.lvl6.proto.StructureInfoProto _structInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"structInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.StructureInfoProto structInfo
    {
      get { return _structInfo; }
      set { _structInfo = value; }
    }

    private int _numResourceOneGenerators = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"numResourceOneGenerators", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numResourceOneGenerators
    {
      get { return _numResourceOneGenerators; }
      set { _numResourceOneGenerators = value; }
    }

    private int _numResourceOneStorages = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"numResourceOneStorages", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numResourceOneStorages
    {
      get { return _numResourceOneStorages; }
      set { _numResourceOneStorages = value; }
    }

    private int _numResourceTwoGenerators = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"numResourceTwoGenerators", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numResourceTwoGenerators
    {
      get { return _numResourceTwoGenerators; }
      set { _numResourceTwoGenerators = value; }
    }

    private int _numResourceTwoStorages = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"numResourceTwoStorages", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numResourceTwoStorages
    {
      get { return _numResourceTwoStorages; }
      set { _numResourceTwoStorages = value; }
    }

    private int _numHospitals = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"numHospitals", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numHospitals
    {
      get { return _numHospitals; }
      set { _numHospitals = value; }
    }

    private int _numResidences = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"numResidences", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numResidences
    {
      get { return _numResidences; }
      set { _numResidences = value; }
    }

    private int _numMonsterSlots = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"numMonsterSlots", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numMonsterSlots
    {
      get { return _numMonsterSlots; }
      set { _numMonsterSlots = value; }
    }

    private int _numLabs = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"numLabs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numLabs
    {
      get { return _numLabs; }
      set { _numLabs = value; }
    }

    private int _pvpQueueCashCost = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"pvpQueueCashCost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pvpQueueCashCost
    {
      get { return _pvpQueueCashCost; }
      set { _pvpQueueCashCost = value; }
    }

    private int _resourceCapacity = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"resourceCapacity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int resourceCapacity
    {
      get { return _resourceCapacity; }
      set { _resourceCapacity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FullUserStructureProto")]
  public partial class FullUserStructureProto : global::ProtoBuf.IExtensible
  {
    public FullUserStructureProto() {}
    

    private int _userStructId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userStructId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userStructId
    {
      get { return _userStructId; }
      set { _userStructId = value; }
    }

    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private int _structId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"structId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int structId
    {
      get { return _structId; }
      set { _structId = value; }
    }

    private long _lastRetrieved = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lastRetrieved", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lastRetrieved
    {
      get { return _lastRetrieved; }
      set { _lastRetrieved = value; }
    }

    private long _purchaseTime = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"purchaseTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long purchaseTime
    {
      get { return _purchaseTime; }
      set { _purchaseTime = value; }
    }

    private bool _isComplete = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"isComplete", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isComplete
    {
      get { return _isComplete; }
      set { _isComplete = value; }
    }

    private com.lvl6.proto.CoordinateProto _coordinates = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"coordinates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.CoordinateProto coordinates
    {
      get { return _coordinates; }
      set { _coordinates = value; }
    }

    private com.lvl6.proto.StructOrientation _orientation = com.lvl6.proto.StructOrientation.NO_ORIENTATION;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"orientation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.StructOrientation.NO_ORIENTATION)]
    public com.lvl6.proto.StructOrientation orientation
    {
      get { return _orientation; }
      set { _orientation = value; }
    }

    private int _fbInviteStructLvl = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"fbInviteStructLvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fbInviteStructLvl
    {
      get { return _fbInviteStructLvl; }
      set { _fbInviteStructLvl = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoordinateProto")]
  public partial class CoordinateProto : global::ProtoBuf.IExtensible
  {
    public CoordinateProto() {}
    

    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }

    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TutorialStructProto")]
  public partial class TutorialStructProto : global::ProtoBuf.IExtensible
  {
    public TutorialStructProto() {}
    

    private int _structId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"structId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int structId
    {
      get { return _structId; }
      set { _structId = value; }
    }

    private com.lvl6.proto.CoordinateProto _coordinate = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"coordinate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.CoordinateProto coordinate
    {
      get { return _coordinate; }
      set { _coordinate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObstacleProto")]
  public partial class ObstacleProto : global::ProtoBuf.IExtensible
  {
    public ObstacleProto() {}
    

    private int _obstacleId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"obstacleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int obstacleId
    {
      get { return _obstacleId; }
      set { _obstacleId = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private com.lvl6.proto.ResourceType _removalCostType = com.lvl6.proto.ResourceType.NO_RESOURCE;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"removalCostType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.ResourceType.NO_RESOURCE)]
    public com.lvl6.proto.ResourceType removalCostType
    {
      get { return _removalCostType; }
      set { _removalCostType = value; }
    }

    private int _cost = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cost
    {
      get { return _cost; }
      set { _cost = value; }
    }

    private int _secondsToRemove = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"secondsToRemove", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int secondsToRemove
    {
      get { return _secondsToRemove; }
      set { _secondsToRemove = value; }
    }

    private int _width = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int width
    {
      get { return _width; }
      set { _width = value; }
    }

    private int _height = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }

    private string _imgName = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"imgName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string imgName
    {
      get { return _imgName; }
      set { _imgName = value; }
    }

    private float _imgVerticalPixelOffset = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"imgVerticalPixelOffset", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float imgVerticalPixelOffset
    {
      get { return _imgVerticalPixelOffset; }
      set { _imgVerticalPixelOffset = value; }
    }

    private string _description = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }

    private float _chanceToAppear = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"chanceToAppear", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float chanceToAppear
    {
      get { return _chanceToAppear; }
      set { _chanceToAppear = value; }
    }

    private string _shadowImgName = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"shadowImgName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string shadowImgName
    {
      get { return _shadowImgName; }
      set { _shadowImgName = value; }
    }

    private float _shadowVerticalOffset = default(float);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"shadowVerticalOffset", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float shadowVerticalOffset
    {
      get { return _shadowVerticalOffset; }
      set { _shadowVerticalOffset = value; }
    }

    private float _shadowHorizontalOfffset = default(float);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"shadowHorizontalOfffset", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float shadowHorizontalOfffset
    {
      get { return _shadowHorizontalOfffset; }
      set { _shadowHorizontalOfffset = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MinimumObstacleProto")]
  public partial class MinimumObstacleProto : global::ProtoBuf.IExtensible
  {
    public MinimumObstacleProto() {}
    

    private int _obstacleId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"obstacleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int obstacleId
    {
      get { return _obstacleId; }
      set { _obstacleId = value; }
    }

    private com.lvl6.proto.CoordinateProto _coordinate = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"coordinate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.CoordinateProto coordinate
    {
      get { return _coordinate; }
      set { _coordinate = value; }
    }

    private com.lvl6.proto.StructOrientation _orientation = com.lvl6.proto.StructOrientation.NO_ORIENTATION;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"orientation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.StructOrientation.NO_ORIENTATION)]
    public com.lvl6.proto.StructOrientation orientation
    {
      get { return _orientation; }
      set { _orientation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserObstacleProto")]
  public partial class UserObstacleProto : global::ProtoBuf.IExtensible
  {
    public UserObstacleProto() {}
    

    private int _userObstacleId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userObstacleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userObstacleId
    {
      get { return _userObstacleId; }
      set { _userObstacleId = value; }
    }

    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private int _obstacleId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"obstacleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int obstacleId
    {
      get { return _obstacleId; }
      set { _obstacleId = value; }
    }

    private com.lvl6.proto.CoordinateProto _coordinates = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"coordinates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.CoordinateProto coordinates
    {
      get { return _coordinates; }
      set { _coordinates = value; }
    }

    private com.lvl6.proto.StructOrientation _orientation = com.lvl6.proto.StructOrientation.NO_ORIENTATION;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"orientation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.StructOrientation.NO_ORIENTATION)]
    public com.lvl6.proto.StructOrientation orientation
    {
      get { return _orientation; }
      set { _orientation = value; }
    }

    private long _removalStartTime = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"removalStartTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long removalStartTime
    {
      get { return _removalStartTime; }
      set { _removalStartTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ResourceType")]
    public enum ResourceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_RESOURCE", Value=4)]
      NO_RESOURCE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CASH", Value=1)]
      CASH = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OIL", Value=2)]
      OIL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GEMS", Value=3)]
      GEMS = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MONSTER", Value=20)]
      MONSTER = 20
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"StructOrientation")]
    public enum StructOrientation
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_ORIENTATION", Value=3)]
      NO_ORIENTATION = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"POSITION_1", Value=1)]
      POSITION_1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"POSITION_2", Value=2)]
      POSITION_2 = 2
    }
  
}